config/routes.rb
Rails.application.routes.draw do

  resources :formations do
    member do
      get 'show_plays'
    end
  end

  resources :roles, only: [:destroy]

  resources :events
  resources :situations
  resources :itineraries
  resources :seasons do
    collection do
      get 'choose'
    end
  end

  get 'calendars/index'

  resources :teams
  resources :games do
    member do
      get 'player_stats'
      post 'player_make_stats'
      get 'game_stats'
      post 'make_game_stats'
    end
  end

  resources :players do
    member do
        get 'print_show'
        get 'show_stats'
        get 'add_position'
        post 'position_added'
    end
  end

  resources :stat_types

  resources :positions do
    put :sort, on: :collection
    collection do
      get 'print_index'
    end
  end

  resources :dashboards
  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  root 'dashboards#index'

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :team
  has_many :situations
  accepts_nested_attributes_for :situations,
      reject_if: :all_blank

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_itinerary, only: [:show, :edit, :update, :destroy]
  before_action :set_team

  # GET /itineraries
  # GET /itineraries.json
  def index
    @itineraries = @team.itineraries
  end

  # GET /itineraries/1
  # GET /itineraries/1.json
  def show
    @tasks = Situation.all
  end

  # GET /itineraries/new
  def new
    @itinerary = Itinerary.new
  end

  # GET /itineraries/1/edit
  def edit
    @itinerary.situations.build
  end

  # POST /itineraries
  # POST /itineraries.json
  def create
    @itinerary = Itinerary.new(itinerary_params)
    @itinerary.update(team: @team)
    respond_to do |format|
      if @itinerary.save
        format.html { redirect_to @itinerary, notice: 'Itinerary was successfully created.' }
        format.json { render :show, status: :created, location: @itinerary }
      else
        format.html { render :new }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itineraries/1
  # PATCH/PUT /itineraries/1.json
  def update
    respond_to do |format|
      if @itinerary.update(itinerary_params)
        format.html { redirect_to @itinerary, notice: 'Itinerary was successfully updated.' }
        format.json { render :show, status: :ok, location: @itinerary }
      else
        format.html { render :edit }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itineraries/1
  # DELETE /itineraries/1.json
  def destroy
    @itinerary.destroy
    respond_to do |format|
      format.html { redirect_to itineraries_url, notice: 'Itinerary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itinerary
      @itinerary = Itinerary.find(params[:id])
    end

    def set_team
      @team = Team.find(current_user.team_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def itinerary_params
      params.require(:itinerary).permit(:name, situations_attributes: [:id, :task, :time])
    end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/itineraries/_form.html.erb
<div class="site-headers">
  <h1>Itinerary</h1>
  <h4>Edit your It<span class="logo-color">i</span>nerary</h4>
</div>

<div class="edit-container itinerary-edition">
  <%= form_for(@itinerary) do |f| %>
    <% if @itinerary.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@itinerary.errors.count, "error") %> prohibited this itinerary from being saved:</h2>

        <ul>
        <% @itinerary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="itinerary-field-name">
      <%= f.label :name %><br>
      <%= f.text_field :name, placeholder: "Itinerary Name" %>
    </div>





    <div class="wrapper">
      <%= f.fields_for(:situations) do |ff| %>
         <div class="situation-fields">
           <div class="itinerary-field">
             <%= ff.label :time %><br>
             <%= ff.text_field :time, placeholder: "Time" %>
           </div>

           <div class="itinerary-field">
             <%= ff.label :task %><br>
             <%= ff.text_field :task, placeholder: "Task" %>
           </div>
         </div>
      <%end%>


    </div>






    <div class="actions">
      <% if current_page?(new_itinerary_path) %>
        <%= f.submit %>
        <button> <%= link_to 'Back', itineraries_path %> </button>
      <%else %>
        <%= f.submit %>
        <button> <%= link_to 'Back', itineraries_path %> </button>
        <button id="addTask">Add Field </button>
        <%= link_to '<i class="fa fa-times fa-2x"></i>'.html_safe, Itinerary.find(params[:id]), method: :delete, data: { confirm: 'Are you sure?' },class: "delete-x"  %>
      <% end  %>
    </div>



  <% end %>
</div>

app/views/itineraries/edit.html.erb
<%= render 'form' %>

app/views/itineraries/index.html.erb
<div class="site-headers">
  <h1>Itineraries</h1>
  <h4>Create It<span class="logo-color">i</span>neraries for Practice and Team Events</h4>
</div>


<div class="itinerary-container">
  <% @itineraries.each do |itinerary|  %>
    <div class="a-card">
      <div class="aheader">
        <h1 ><%= link_to itinerary.name, itinerary  %>
          <div class="right-icon"><%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_itinerary_path(itinerary) %></div>
        </h1>
      </div>
      <div class="somecontent">
        <% itinerary.situations.each do |s| %>
          <section>
            <aside><%= s.time %></aside>
            <article><%= s.task %></article>
          </section>
        <% end  %>

      </div>
    </div>
  <% end %>
  <div id="itinerary-button">
    <%= link_to '<button>New Itinerary</button>'.html_safe, new_itinerary_path %>
  </div>
</div>

app/views/itineraries/new.html.erb
<%= render 'form' %>

app/views/itineraries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show-container">
  <p>
    <strong>Name:</strong>
    <%= @itinerary.name %>
  </p>

<% @itinerary.situations.each do |s| %>
    <div id="show-itinerary-list"> <%= s.time  %> <%= s.task %> </div>
<%end  %>
  <%= link_to 'Edit', edit_itinerary_path(@itinerary) %> |
  <%= link_to 'Back', itineraries_path %>
</div>