config/routes.rb
Rails.application.routes.draw do

  resources :formations do
    member do
      get 'show_plays'
    end
  end

  resources :roles, only: [:destroy]

  resources :events
  resources :situations
  resources :itineraries
  resources :seasons do
    collection do
      get 'choose'
    end
  end

  get 'calendars/index'

  resources :teams
  resources :games do
    member do
      get 'player_stats'
      post 'player_make_stats'
      get 'game_stats'
      post 'make_game_stats'
    end
  end

  resources :players do
    member do
        get 'print_show'
        get 'show_stats'
        get 'add_position'
        post 'position_added'
    end
  end

  resources :stat_types

  resources :positions do
    put :sort, on: :collection
    collection do
      get 'print_index'
    end
  end

  resources :dashboards
  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  root 'dashboards#index'

end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :roles
  has_many :players, through: :roles

  def get_team_players(team)
    team_roles = roles.order(:depth_chart_position).joins(:player).where("players.team_id = #{team.id}")
    team_roles.map &:player
  end

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]
  before_action :set_team
  layout "print", only: :print_index


  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  def print_index
    @positions = Position.all
    render 'index'
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  def sort
    params[:order].each do |key,value|
      Role.find(value[:id]).update(depth_chart_position: value[:position])
    end
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    def set_team
      @team = Team.find(current_user.team_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper

  def capitalize_name(first_name, last_name)
    name = ""
    name += first_name.capitalize + " "
    name += last_name.capitalize
    return name
  end

end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<div class="depth-chart">
  <div class="site-headers">
    <h1>Depth Chart</h1>
    <h4>Manage Your Team Depth Chart Pos<span class="logo-color">i</span>tions</h4>
  </div>
  <div class="cards">
    <% @positions.each do |position| %>
    <div class="card">
      <div class="card-image">
        <img src='<%= asset_path("position_#{position.id}.jpg") %>' alt="">
      </div>
      <div class="card-header">
        <%= position.code %>
      </div>
      <div class="card-copy">
        <ul class="sortable">
        <% position.get_team_players(@team).each do |player| %>
          <% player.roles.where(position_id: position.id).each do |r| %>
            <li class="ui-state-default", data-id="<%= r.id %>"><i class="fa fa-sort"></i> <%= link_to "#{r.get_player_name}", show_stats_player_path(r.get_player) %></li>
          <% end %>
        <% end %>
      </ul>
      </div>
    </div>
    <% end %>
</div>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<div class="show-container"

<p>
  <strong>Name:</strong>
  <%= @position.name %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>