config/routes.rb
Rails.application.routes.draw do

  resources :formations do
    member do
      get 'show_plays'
    end
  end

  resources :roles, only: [:destroy]

  resources :events
  resources :situations
  resources :itineraries
  resources :seasons do
    collection do
      get 'choose'
    end
  end

  get 'calendars/index'

  resources :teams
  resources :games do
    member do
      get 'player_stats'
      post 'player_make_stats'
      get 'game_stats'
      post 'make_game_stats'
    end
  end

  resources :players do
    member do
        get 'print_show'
        get 'show_stats'
        get 'add_position'
        post 'position_added'
    end
  end

  resources :stat_types

  resources :positions do
    put :sort, on: :collection
    collection do
      get 'print_index'
    end
  end

  resources :dashboards
  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  root 'dashboards#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  
  has_many :roles
  accepts_nested_attributes_for :roles
  has_attached_file :uploaded_file
  validates_attachment_content_type :uploaded_file, :content_type => /\Aimage\/.*\Z/

  has_many :memberships
  has_many :games, :through => :memberships
  has_many :positions, :through => :roles
  belongs_to :class_status
  has_many :stats
  belongs_to :team

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def get_stat_types
    if positions.count < 2
      if positions.first.id <= 8
        StatType.where(id: 1..23)
      elsif positions.first.id <= 14
        StatType.where(id: 24.. 34)
      else
        StatType.where(id: 35..54)
      end
    else
      StatType.all
    end
  end

  def primary_position_name
    positions.blank? ? "N/A" : positions.first.name
  end

  def class_name
    class_status.blank? ? "N/A" : class_status.name
  end

  def total_rush_yards
    stats.where(stat_type_id: 10).sum(:value)
  end

  def self.lead_player_for(stat_type)
    best_stat = stat_type.stats.order(:value).last

    player_name = (best_stat ? best_stat.player.full_name : "N/A")
    value = (best_stat ? best_stat.value.to_i : 0)
    return {player_name: player_name, value: value}
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy, :stats, :make_stats, :show_stats, :add_position, :position_added, :print_show]
  before_action :set_positions_and_statuses, only: [:new, :edit, :create, :index, :add_position]
  before_action :set_team
  layout "print", only: :print_show

  # GET /players
  # GET /players.json
  def index
    @players = @team.players.order(:last_name)
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  def print_show
    render "show"
  end

  def add_position
  end

  def position_added
    @player.positions << Position.find(params[:position][:position_id])
    redirect_to players_path
  end

  def show_stats
    @games = @team.games
  end

  # GET /players/new
  def new
    @player = Player.new
    @player.roles.build
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    respond_to do |format|
      if @player.save
        @player.update(team_id: @team.id)
        role = Role.get_role(params, @player)
        role.update(depth_chart_position: role.next_available)
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, locals: { :positions => @positions, :class_statuses => @class_statuses} }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    def set_team
      @team = Team.find(current_user.team_id)
    end

    def set_positions_and_statuses
      @positions = Position.all
      @class_statuses = ClassStatus.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:first_name, :last_name, :jersey_number, :phone_number, :email, :weight, :height, :position_ids,
                                     :class_status_id, :game_id, :uploaded_file,
                                     roles_attributes: [ :position_id ])
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_add_position.html.erb
<%= form_tag("players/#{id}/position_added", :action => "position_added") do %>


  <div class="field">
    <h2>Add Position</h2>
    <%= label_tag :position %>
    <%= collection_select :position, :position_id, positions.to_a.collect, :id, :name %>
  </div>

  <div id="role-modal">
    <h2>Edit Positions</h2>
    <% player = Player.find(id) %>

    <% player.roles.each do |r| %>

      <p><%= r.position.code %> <%= link_to "Remove Position", r, data: {confirm: 'are you sure?'}, method: :delete %></p>

    <%  end %>
  </div>

  <%= submit_tag "Press Me" %>
<% end %>

app/views/players/_edit_form.html.erb
<div class="site-headers">
  <h1>Roster</h1>
  <h4>Create and Ed<span class="logo-color">i</span>t Player Information </h4>
</div>
<div class="edit-container">
    <%= form_for(@player) do |f| %>
      <% if @player.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

          <ul>
          <% @player.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, placeholder:"First Name" %>
      </div>
      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, placeholder:"Last Name" %>
      </div>
      <div class="field">
        <%= f.label :jersey_number %><br>
        <%= f.number_field :jersey_number, placeholder:"Jersey Number" %>
      </div>
      <div class="field">
        <%= f.label :phone_number %><br>
        <%= f.text_field :phone_number, placeholder:"Phone Number" %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, placeholder:"Email" %>
      </div>
      <div class="field">
        <%= f.label :weight %><br>
        <%= f.text_field :weight, placeholder:"Weight" %>
      </div>
      <div class="field">
        <%= f.label :height %><br>
        <%= f.text_field :height, placeholder:"Height" %>
      </div>
      <div class="field">
        <%= f.label :class_status_id %><br>
        <%= f.collection_select :class_status_id, @class_statuses.to_a.collect, :id, :name %>
      </div>

      <div class="field">
        <%= f.label :upload_profile_picture %><br>
        <%= f.file_field 'uploaded_file' %>
      </div>



      <div class="actions">
        <%= f.submit %>
        <%= link_to '<i class="fa fa-times fa-2x"></i>'.html_safe, @player, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        </tr>
      </div>


    <% end %>
</div>

app/views/players/_form.html.erb
<div class="edit-container">
    <%= form_for(@player) do |f|%>
      <% if @player.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

          <ul>
          <% @player.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, placeholder:"First Name" %>
      </div>
      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, placeholder:"Last Name" %>
      </div>
      <div class="field">
        <%= f.label :jersey_number %><br>
        <%= f.number_field :jersey_number, placeholder:"Jersey Number" %>
      </div>
      <div class="field">
        <%= f.label :phone_number %><br>
        <%= f.text_field :phone_number, placeholder:"Phone Number" %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, placeholder:"Email" %>
      </div>
      <div class="field">
        <%= f.label :weight %><br>
        <%= f.text_field :weight, placeholder:"Weight" %>
      </div>
      <div class="field">
        <%= f.label :height %><br>
        <%= f.text_field :height, placeholder:"Height" %>
      </div>
      <%= f.fields_for(:roles) do |ff| %>
        <div class="field">
          <%= ff.label :position_id %><br>
          <%= ff.collection_select :position_id, @positions.to_a.collect, :id, :name %>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :class_status_id %><br>
        <%= f.collection_select :class_status_id, @class_statuses.to_a.collect, :id, :name %>
      </div>

      <div class="field">
        <%= f.label :upload_profile_picture %><br>
        <%= f.file_field :uploaded_file %>
      </div>


      <div class="actions">
        <%= f.submit %>
      </div>


    <% end %>
</div>

app/views/players/add_position.html.erb
<div id="add-position">
  <h3>Delete Position</h3>
  <%= form_tag(position_added_player_path) do %>
  <% @player.roles.each do |r| %>
    <p>
      <%= r.position.code %>: <%= link_to '<i class="fa fa-times fa-2x"></i>'.html_safe, r, method: :delete, data: {confirm: 'are you sure?'} %>
    </p>
  <% end %>
  <h3>Add Position</h3>
    <div class="field">
      <div id="select-div"><%= collection_select :position, :position_id, @positions.to_a.collect, :id, :name %></div>
    </div>
    <%= submit_tag "Add Position"%>
  <% end %>
</div>

app/views/players/edit.html.erb
 <%= render 'edit_form' %>

app/views/players/index.html.erb
<div id="player-index">
  <div class="site-headers">
    <h1>Roster</h1>
    <h4>Create and Ed<span class="logo-color">i</span>t Player Information </h4>
  </div>
  <table class="tables">
    <thead>
      <tr>
        <th colspan="2">Name</th>
        <th>Jersey number</th>
        <th colspan="2">Contact </th>
        <th>Weight</th>
        <th>Height</th>
        <th>Position</th>
        <th>Class status</th>
        <th colspan="4">Table Options</th>
      </tr>
    </thead>


    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td colspan="2"><%= player.first_name %> <%= player.last_name %></td>
          <td><%= player.jersey_number %></td>
          <td colspan="2"><%= player.phone_number %><br>
               <%= player.email %>
          </td>
          <td><%= player.weight %></td>
          <td><%= player.height %></td>
          <td>
          <% player.positions.each do |p| %>
            <%= p.name %>
          <% end %>
          </td>
          <td><%= player.class_status.name %></td>
          <td><%= link_to 'Athlete Info', player %></td>
          <td><%= link_to 'Edit/Add Positions', add_position_player_path(player) %>

          </td>
          <td><%= link_to "Show Stats", show_stats_player_path(player) %></td>
          <td class="icons"><%= link_to '<i class="fa fa-pencil-square-o "></i>'.html_safe, edit_player_path(player) %> <%# link_to '<i class="fa fa-times fa-2x"></i>'.html_safe, player, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to '<button class="form-button">New Player</button>'.html_safe, new_player_path %>

</div>

app/views/players/new.html.erb
<div class="site-headers">
  <h1>Add a New Player</h1>
  <h4>Enter Information for a New Player</h4>
</div>

<%= render 'form' %>

app/views/players/show.html.erb
<div class="site-headers">
  <h1>Player Information</h1>
  <h4>Showing Informat<span class="logo-color">i</span>on for <%= @player.first_name %> <%= @player.last_name %></h4>
</div>
<div class="show-container">
  <h3> <%= @player.first_name %> <%= @player.last_name %>:  <%= @player.primary_position_name %></h3>
    <br>
  <div class="side-image-container"></div>
  <ul class="show-list">

        <% if @player.uploaded_file_file_name %>
        <li>
          <%= image_tag @player.uploaded_file %>
        </li>
        <% end %>

        <li>
          <strong>Jersey number:</strong>
          <%= @player.jersey_number %>
        </li>

        <li>
          <strong>Phone number:</strong>
          <%= @player.phone_number %>
        </li>

        <li>
          <strong>Email:</strong>
          <%= @player.email %>
        </li>

        <li>
          <strong>Weight:</strong>
          <%= @player.weight %>
        </li>

        <li>
          <strong>Height:</strong>
          <%= @player.height %>
        </li>

        <li>
          <strong>Positions:</strong>
          <% @player.positions.each do |p| %>
            <%= p.name %>
          <% end %>
        </li>

        <li>
          <strong>Class status:</strong>
          <%= @player.class_name %>
        </li>



  </ul>
  <div class="nav-bottom">
    <%= link_to 'Edit', edit_player_path(@player) %> |
    <%= link_to 'Back', players_path %>
    <%= link_to "<i class='fa fa-print'></i>".html_safe, print_show_player_path(@player) %>
  </div>
</div>

app/views/players/show_stats.html.erb
<div class="show-player-stats">

<div class="site-headers">
  <h1> <%= @player.positions.first.name %> <%= @player.first_name %> <%= @player.last_name %></h1>
  <h4>Show<span class="logo-color">i</span>ng Game Stats for <%= @player.first_name %> <%= @player.last_name %> </h4>
</div>
<% @games.each do |g| %>

    <table class="tables">
      <h3><%= g.opponent %></h3>
      <thead>
        <tr>
      <% g.stats.where(player_id: @player.id).each do |s| %>
          <th><%= s.stat_type.name %></td>
      <% end %>
        </tr>
      </thead>
        <tr>
      <% g.stats.where(player_id: @player.id).each do |s| %>
         <td><%= s.value %></td>
      <% end %>
        </tr>
    </table>

<% end %>

</div>