config/routes.rb
Rails.application.routes.draw do

  resources :formations do
    member do
      get 'show_plays'
    end
  end

  resources :roles, only: [:destroy]

  resources :events
  resources :situations
  resources :itineraries
  resources :seasons do
    collection do
      get 'choose'
    end
  end

  get 'calendars/index'

  resources :teams
  resources :games do
    member do
      get 'player_stats'
      post 'player_make_stats'
      get 'game_stats'
      post 'make_game_stats'
    end
  end

  resources :players do
    member do
        get 'print_show'
        get 'show_stats'
        get 'add_position'
        post 'position_added'
    end
  end

  resources :stat_types

  resources :positions do
    put :sort, on: :collection
    collection do
      get 'print_index'
    end
  end

  resources :dashboards
  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  root 'dashboards#index'

end

app/models/formation.rb
class Formation < ActiveRecord::Base
  belongs_to :team

  has_attached_file :pdf_file
  validates_attachment_content_type :pdf_file, content_type: ['image/jpeg', 'image/png', 'application/pdf']
  
end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController
  before_action :set_formation, only: [:show, :edit, :update, :destroy, :show_plays]
  before_action :set_team

  # GET /formations
  # GET /formations.json
  def index
    @formations = @team.formations
  end

  # GET /formations/1
  # GET /formations/1.json
  def show
  end

  # GET /formations/new
  def new
    @formation = Formation.new
  end

  # GET /formations/1/edit
  def edit
  end

  def show_plays

  end

  # POST /formations
  # POST /formations.json
  def create
    @formation = Formation.new(formation_params)

    respond_to do |format|
      if @formation.save
        @formation.update(team: @team)
        format.html { redirect_to @formation, notice: 'Formation was successfully created.' }
        format.json { render :show, status: :created, location: @formation }
      else
        format.html { render :new }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formations/1
  # PATCH/PUT /formations/1.json
  def update
    respond_to do |format|
      if @formation.update(formation_params)
        format.html { redirect_to @formation, notice: 'Formation was successfully updated.' }
        format.json { render :show, status: :ok, location: @formation }
      else
        format.html { render :edit }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formations/1
  # DELETE /formations/1.json
  def destroy
    @formation.destroy
    respond_to do |format|
      format.html { redirect_to formations_url, notice: 'Formation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formation
      @formation = Formation.find(params[:id])
    end

    def set_team
      @team = Team.find(current_user.team_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formation_params
      params.require(:formation).permit(:team_id, :name, :pdf_file)
    end
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/views/formations/_form.html.erb
<div class="site-headers">
  <h1>Formation</h1>
  <h4>Create a Format<span class="logo-color">i</span>on to Upload Plays</h4>
</div>

<div class="edit-container">
  <%= form_for(@formation) do |f| %>
    <% if @formation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@formation.errors.count, "error") %> prohibited this formation from being saved:</h2>

        <ul>
        <% @formation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, placeholder: "Formation" %>
    </div>
    <div class="field">
      <%= f.label :pdf_file %><br>
      <%= f.file_field :pdf_file %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/formations/edit.html.erb
<h1>Editing Formation</h1>

<%= render 'form' %>

<%= link_to 'Show', @formation %> |
<%= link_to 'Back', formations_path %>

app/views/formations/index.html.erb
<div class="site-headers">
  <h1> Manage Playbook </h1>
  <h4> Create a Format<span class="logo-color">i</span>on and Upload PDFs to Your Formation</h4>
</div>

<table class="tables">
  <thead>
    <tr>
      <th>Name</th>
      <th>Uploaded</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tbody>
    <% @formations.each do |formation| %>
      <tr>
        <td><%= formation.name %></td>
        <td><%= formation.created_at.strftime('%B %d, %Y') %></td>
        <td><%= link_to 'Show Plays', formation.pdf_file.url, remote: true, class: "pdf-lightbox" %></td>
        <td><%= link_to 'Edit', edit_formation_path(formation) %></td>
        <td><%= link_to 'Destroy', formation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="show-plays"></div>

<%= link_to 'New Formation', new_formation_path %>

app/views/formations/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', formations_path %>

app/views/formations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @formation.name %>
</p>

    <p>
      <%= link_to "Show Plays", @formation.pdf_file.url %>
    </p>



<%= link_to 'Edit', edit_formation_path(@formation) %> |
<%= link_to 'Back', formations_path %>